/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apppackage;

/**
 *
 * @author Eigenaar
 */
public class NegativeReactions extends javax.swing.JFrame {

    /**
     * Creates new form NegativeReactions
     */
    public NegativeReactions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backNegativeReactions = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        FileMainmenu = new javax.swing.JMenuItem();
        FileExitmenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Helptipmenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Database manager Ahoy");

        backNegativeReactions.setText("Back");
        backNegativeReactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backNegativeReactionsActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        FileMainmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        FileMainmenu.setText("Main");
        FileMainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMainmenuActionPerformed(evt);
            }
        });
        jMenu1.add(FileMainmenu);

        FileExitmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        FileExitmenu.setText("Exit");
        FileExitmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileExitmenuActionPerformed(evt);
            }
        });
        jMenu1.add(FileExitmenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        Helptipmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        Helptipmenu.setText(" Tips");
        Helptipmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelptipmenuActionPerformed(evt);
            }
        });
        jMenu2.add(Helptipmenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(590, Short.MAX_VALUE)
                .addComponent(backNegativeReactions, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addComponent(backNegativeReactions, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backNegativeReactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backNegativeReactionsActionPerformed
    GraphChoose graphChoose = new GraphChoose();
    graphChoose.setVisible(true);
    NegativeReactions.this.dispose();
    }//GEN-LAST:event_backNegativeReactionsActionPerformed

    private void HelptipmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelptipmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelptipmenuActionPerformed

    private void FileMainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMainmenuActionPerformed
    LoginScreen lgn = new LoginScreen();
    lgn.setVisible(true);
    NegativeReactions.this.dispose();
    }//GEN-LAST:event_FileMainmenuActionPerformed

    private void FileExitmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileExitmenuActionPerformed
    NegativeReactions.this.dispose();
    }//GEN-LAST:event_FileExitmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NegativeReactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NegativeReactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NegativeReactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NegativeReactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NegativeReactions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem FileExitmenu;
    private javax.swing.JMenuItem FileMainmenu;
    private javax.swing.JMenuItem Helptipmenu;
    private javax.swing.JButton backNegativeReactions;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
